default:
  tags:
    - nix

mypy:
  script:
    - nix develop .#with-build-tools --command mypy amarcord tests

pyright:
  script:
    - nix develop .#with-build-tools --command pyright

pylint:
  script:
    - nix develop .#with-build-tools --command pylint amarcord tests

isort:
  script:
    - nix develop .#with-build-tools --command isort --check amarcord tests

fawltydeps:
  script:
    - nix develop .#with-build-tools --command fawltydeps

check-shell-scripts:
   script:
     - nix develop .#with-build-tools --command shellcheck ci/*.sh

elm-review:
  script:
    - ci/elm-review.sh

build-docker-image:
  script:
    - ci/nix-build-docker-image.sh

nix-pin-latest:
  script:
    - nix build --out-link ~/pipeline-pins/amarcord-python-package .#amarcord-python-package
  only:
    - master

nix-pin-latest-manual:
  script:
    - nix build --out-link ~/pipeline-pins/amarcord-python-package-$CI_COMMIT_REF_SLUG .#amarcord-python-package
  when: manual

check-requirements:
   script:
     - nix develop --command ./ci/check-requirements.sh
tests:
  script:
    - nix develop .#with-build-tools --command ci/run-tests.sh
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
