default:
  tags:
    - nix

mypy:
  script:
    - nix-shell default.nix -A pythonPackage --run "mypy amarcord tests"

pylint:
  script:
    - nix-shell default.nix -A pythonPackage --run "pylint amarcord tests"

isort:
  script:
    - nix-shell default.nix -A pythonPackage --run "isort --check amarcord tests"

check-shell-scripts:
   script:
     - nix-shell -p shellcheck --run "shellcheck ci/*.sh"

build-docker-image:
  script:
    - ci/nix-build-docker-image.sh

nix-pin-latest:
  script:
    - nix-build default.nix -A pythonPackage --out-link ~/pipeline-pins/amarcord-python-package
    - nix-build default.nix -A frontend --out-link ~/pipeline-pins/amarcord-elm-package
  only:
    - master

nix-pin-latest-manual:
  script:
    - nix-build default.nix -A pythonPackage --out-link ~/pipeline-pins/amarcord-python-package
    - nix-build default.nix -A frontend --out-link ~/pipeline-pins/amarcord-elm-package
  when: manual

check-requirements:
   script:
     - nix-shell -p poetry --run ./ci/check-requirements.sh
tests:
  script:
    - nix-shell default.nix -A pythonPackage --run ci/run-tests.sh
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
