[tool.poetry]
name = "amarcord"
version = "1.0.0"
description = "A ModulAR CollectOR of metaData - serial edition"
authors = ["Philipp Middendorf <philipp.middendorf@desy.de>", "CFEL-SC <sc@cfel.de>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
# for general DB access
SQLAlchemy = { version = "1.4.31", extras = ["mypy", "asyncio"] }
# for mysql
pymysql = '1.0.2'
# for caching_sha2_password access in MySQL
cryptography = '3.4.8'
# for migrating a DB
alembic = '1.7.5'
# for attributi: parsing/printing a delta
isodate = '0.6.0'
# for the config file
PyYAML = '5.4.1'
# for accessing XDG_CONFIG_HOME in the config file for example
xdg = '5.1.1'
# For parsing the arguments for programs (always required basically)
typed-argument-parser = '1.7.2'
# For the config file
pydantic = '1.8.2'
# numpy for Karabo statistics
numpy = { version = '1.21.4' }
# for zmq access in the daemon
pyzmq = '22.3.0'
# for plotting
pandas = '1.3.4'
# For printing "x second(s) ago" in the comments
humanize = '3.12.0'
# For validating units
pint = '0.16.1'
# for the daemon
karabo-bridge = "0.6.1"
# for the daemon
msgpack = "1.0.2"
# for the daemon
msgpack-types = "0.1.0"
# for offline ingest
EXtra-data = "1.8.1"
# for SLURM REST
requests = "2.26.0"

# disabled for now, it's a huge dependency
# kamzik3 = "0.7.7"

# for correcting UTC timezone for dates
python-dateutil = "2.8.2"
types-python-dateutil = "2.8.3"
tqdm = "4.62.3"
# for the webserver
quart = "0.16.2"
# for the webserver
Quart-CORS = "0.5.0"
# asynchronous db client
aiosqlite = "0.17.0"
# asynchronous db client
asyncmy = "0.2.3"
# for time zone detection and conversion of timestamps in attributi
pytz = "2021.3"
types-pytz = "2021.3.4"
# to test incoming files for their mime types
python-magic = "0.4.24"
# to parse/coparse toml files for xwiz
toml = "0.10.2"
# For the experiment simulator
randomname = "0.1.5"
# For the experiment simulator
essential-generators = "1.0"

[tool.poetry.dev-dependencies]
black = '21.9b0'
mypy = '0.930'
pylint = '2.12.2'
pyfakefs = '4.5.3'
pytest = '6.2.5'
hypothesis = '6.27.1'
pytest-cov = '2.12.1'
# slurm
types-requests = "2.26.0"
# config file
types-PyYAML = '5.4.12'
pytest-asyncio = "0.17.2"

[tool.poetry.scripts]
amarcord-karabo-bridge-daemon = "amarcord.cli.karabo_bridge_daemon:main"
amarcord-cfel-analysis-daemon = "amarcord.cli.cfel_analysis_daemon:main"
amarcord-webserver = "amarcord.cli.webserver:main"
amarcord-kamzik-daemon = "amarcord.cli.kamzik_zmq_async_daemon:main"
amarcord-xfel-filesystem-ingester = "amarcord.cli.xfel_filesystem_ingester:main"
amarcord-karabo-online-ingester = "amarcord.cli.karabo_online_ingester:main"
amarcord-karabo-bridge-dumper = "amarcord.cli.karabo_bridge_dumper:main"
amarcord-analysis-daemon = "amarcord.cli.analysis_daemon:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
