* AMARCORD — XFEL edition™
** How to access AMARCORD from a script

We’ve created the =amarcord.amici= Python package containing functions to access an AMARCORD database from within your scripts. Check the package source to see the available functions.

To start using =amarcord.amici=, you can use the following =pip= command:

#+begin_example
pip install --upgrade --index-url https://maxwell-token:JUX_f_ivQjyZbxZAEPYi@gitlab.desy.de/api/v4/projects/370/packages/pypi/simple --no-deps amarcord-amici
#+end_example

Note that this uses a generated token called =maxwell-token= to access the GitLab Python package registry. Two notes on that:

- Ideally, don’t share this URL with people outside XFEL/DESY for now. We’re working on making this package public, but we’re not there yet.
- You can only =pip install= when you have access to =gitlab.desy.de=.
** How to start the AMARCORD GUI

It /should/ ideally be simple:

#+begin_example
pip install -r < requirements.txt
python amarcord/xfel_gui.py
#+end_example

Depending on your operating system, you might have to install Qt 5 or pyqt-5 separately. I’ll add some notes on that later.

To also query Karabo, start the simulator:

#+begin_example
karabo-bridge-server-sim 4545
#+end_example

And add the following lines to your =config.yml=:

#+begin_src yaml
karabo:
  server_url: tcp://localhost:4545
#+end_src
