"""Initial revision

Revision ID: cc54b2d4ceae
Revises:
Create Date: 2021-04-06 10:44:56.465016

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc54b2d4ceae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Attributo",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("suffix", sa.String(length=255), nullable=True),
        sa.Column(
            "associated_table",
            sa.Enum("RUN", "SAMPLE", name="associatedtable"),
            nullable=False,
        ),
        sa.Column("json_schema", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name", "associated_table"),
    )
    op.create_table(
        "Proposal",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("admin_password", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Sample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("attributi", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["proposal_id"], ["Proposal.id"], use_alter=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("sample_id", sa.Integer(), nullable=True),
        sa.Column("attributi", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["Proposal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["Sample.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "RunComment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("comment_text", sa.String(length=255), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["Run.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "EventLog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.Column(
            "level",
            sa.Enum("INFO", "WARNING", "ERROR", name="eventloglevel"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("RunComment")
    op.drop_table("DataSource")
    op.drop_table("Run")
    op.drop_table("Sample")
    op.drop_table("Proposal")
    op.drop_table("Attributo")
    op.drop_table("EventLog")
    # ### end Alembic commands ###
