"""
This type stub file was generated by pyright.
"""

import functools
from .core import *
from . import util

def main(): # -> None:
    ...

def prints(func): # -> (*a: Unknown, **kw: Unknown) -> None:
    ...

